export default {
  avatar_enabled: true,
  avatar_size: '200px',
  avatar_shape: 'circle',
  date_enabled: true,
  time_enabled: true,
  hostname_enabled: true,
  command_shutdown_enabled: true,
  command_reboot_enabled: true,
  command_hibernate_enabled: true,
  command_sleep_enabled: true,
  command_icons_enabled: true,
  command_text_align: 'left',
  style_command_background_color: 'hsl(0, 80%, 26%)',
  style_command_icon_color: 'hsl(13, 100%, 53%)',
  style_command_text_color: 'hsl(0, 0%, 100%)',
  style_login_border_color: 'hsla(46, 82%, 48%, 0.24)',
  style_login_border_enabled: true,
  style_login_button_color: 'hsla(0, 100%, 85%, 0.22)',
  style_login_gradient_top_color: 'hsl(14, 100%, 53%)',
  style_login_gradient_bottom_color: 'hsl(35, 95%, 56%)',
  style_login_username_color: 'hsla(0, 100%, 100%, 1)',
  window_border_radius: '4px',
  window_font_size: '1em',
  window_box_shadow_enabled: false
};
