export default {
  avatar_enabled: true,
  avatar_size: '200px',
  avatar_shape: 'circle',
  date_enabled: true,
  date_format: '<em>%A</em>, the <em>%o</em> of <em>%B</em>',
  time_enabled: true,
  time_format: '%H:%M',
  hostname_enabled: true,
  command_shutdown_enabled: true,
  command_reboot_enabled: true,
  command_hibernate_enabled: true,
  command_sleep_enabled: true,
  command_icons_enabled: true,
  command_text_align: 'left',
  style_command_background_color: 'hsla(0, 2%, 98%, 0.29)',
  style_command_icon_color: 'hsl(182, 79%, 58%)',
  style_command_text_color: 'hsla(0, 0%, 100%, 0.9)',
  style_login_border_color: 'hsla(0, 0%, 0%, 0)',
  style_login_border_enabled: false,
  style_login_button_color: 'hsla(0, 0%, 0%, 0.45)',
  style_login_gradient_top_color: 'hsla(0, 0%, 100%, 0)',
  style_login_gradient_bottom_color: 'hsla(0, 0%, 100%, 0.32)',
  style_login_username_color: 'hsla(0, 100%, 100%, 1)',
  window_border_radius: '4px',
  window_font_size: '1em'
};
