export default {
  avatar_enabled: true,
  avatar_size: '200px',
  avatar_shape: 'circle',
  font_scale: '1',
  date_enabled: true,
  time_enabled: true,
  hostname_enabled: true,
  command_shutdown_enabled: true,
  command_reboot_enabled: true,
  command_hibernate_enabled: true,
  command_sleep_enabled: true,
  command_icons_enabled: true,
  command_text_align: 'left',
  style_command_background_color: 'hsl(123, 43%, 39%)',
  style_command_icon_color: 'hsl(88, 50%, 53%)',
  style_command_text_color: 'hsl(0, 0%, 100%)',
  style_login_border_color: 'hsla(0, 0%, 68%, 0.1)',
  style_login_border_enabled: true,
  style_login_button_color: 'hsla(0, 0%, 0%, 0.49)',
  style_login_gradient_top_color: 'hsl(122, 39%, 49%)',
  style_login_gradient_bottom_color: 'hsl(122, 39%, 49%)',
  style_login_username_color: 'hsla(0, 100%, 100%, 1)',
  window_border_radius: '4px',
  window_font_size: '1em',
  window_box_shadow_enabled: true
};
